apiVersion: v1
kind: Pod
metadata:
  name: myapp-nginx-pod
  labels:
    name: myapp-nginx
    tier: front-end-app
spec:
  containers:
    - name: myapp-nginx-containers
      image: nginx
      ports:
        - containerPort: 80