apiVersion: v1
kind: Service
metadata:
  name: myapp-nginx-service
  labels:
    name: myapp-nginx
    tier: front-end-app
spec:
  selector:
    name: myapp-nginx
    tier: front-end-app
  
  type: NodePort

  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007 # 30000 - 32767